name: Build WEB101
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: First compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          compiler: lualatex
          args: -shell-escape

      - name: bibtex
        run: bibtex web101.aux

      - name: Second compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          compiler: lualatex
          args: -shell-escape

      - name: Third compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          compiler: lualatex
          args: -shell-escape

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./WEB101.pdf